# @import ../common/setup.http
@host = {{base_host}}/v201

### Listing Menu Items (Public)
GET /menu

### Login as Sandy via cookie authentication
POST /auth/login
Content-Type: application/json

{
    "email": "sandy@bikinibottom.sea",
    "password": "fullStackSquirr3l!"
}

### Listing Sandy's Account Info
GET /account/info

### Listing Sandy's Balance Before New Order
GET /account/credits

### Listing Sandy's Orders via Basic Auth
GET /orders


### Create a new cart and add items to it
# @name cart
POST /cart

### Add items to the cart
POST /cart/{{cart.cart_id}}/items
Content-Type: application/json

{
  "item_id": "1"
}

### Checkout the cart
# @name order
POST /cart/{{cart.cart_id}}/checkout
Content-Type: application/x-www-form-urlencoded

tip=-1&delivery_address=Chum Backet Restaurant

### Refund the order: should not work, because the amount is more than the order total
POST /orders/{{order.order_id}}/refund
Content-Type: application/x-www-form-urlencoded

amount=50

### Refund the order: should work
POST /orders/{{order.order_id}}/refund
Content-Type: application/x-www-form-urlencoded

amount=1

### Listing Sandy's Orders via Cookies
GET /orders
