# @import ../common/setup.http
@host = {{base_host}}/v201
@mailpit = http://127.0.0.1:8025/api/v1

### Reset database for clean state
{{
  await resetDB("v201");
  console.info("🔄 Database reset to clean state");
}}

### Listing Menu Items (Public)
GET /menu

### Create a new user: should be already taken
POST /auth/register
Content-Type: application/json

{
    "email": "spongebob@krusty-krab.sea"
}

?? status == 400
?? js response.parsedBody.error == email already taken


### Create a new user
POST /auth/register
Content-Type: application/json

{
    "email": "plankton.jr@chum-bucket.sea"
}

?? status == 200
?? js response.parsedBody.email == plankton.jr@chum-bucket.sea


### Get the token
GET {{mailpit}}/messages?limit=1

@message_id = {{response.parsedBody.messages.at(-1).ID}}

### Extract the token
GET {{mailpit}}/message/{{message_id}}

@token = {{response.parsedBody.Text.match(/token=([a-zA-Z0-9\-_.]+)/)[1]}}


### Should fail
# @prompt token Get the token from verification email, using Mailpit UI: http://127.0.0.1:8025/
POST /auth/register
Content-Type: application/json

{
    "token": "{{token}}",
    "email": "spongebob@krusty-krab.sea",
    "password": "hijacked",
    "name": "SpongeBob"
}

?? status == 200
?? js response.parsedBody.email == plankton.jr@chum-bucket.sea


###
GET /account/info
Authorization: Basic plankton.jr@chum-bucket.sea:hijacked

?? status == 200
?? js response.parsedBody.email == plankton.jr@chum-bucket.sea
