# @import ../common/setup.http
@host = {{base_host}}/v301

###
GET /restaurants

### Plankton creates a cart in Krusty Krab and adds a krabby patty to it
# NOTE: New argument, restaurant_id is **required**!
# Note #2: Plankton is using his customer credentials to create the cart, he does not login, so there is no session.
{{
  await seedBalance("v301", "plankton@chum-bucket.sea", 100);
}}
POST /cart?restaurant_id=1
Authorization: {{plankton_auth}}

@cart_id = {{response.parsedBody.cart_id}}

###
POST /cart/{{cart_id}}/items
Content-Type: application/json
Authorization: {{plankton_auth}}

{
  "item_id": "4"
}

### Plankton checks out the cart and creates an order (so far so good)
POST /cart/{{cart_id}}/checkout
Content-Type: application/x-www-form-urlencoded
Authorization: {{plankton_auth}}

tip=1&delivery_address=Chum Backet Restaurant

@order_id = {{response.parsedBody.order_id}}


### Krusty Krab processes and delivers the order
PATCH /orders/{{order_id}}/status
X-API-Key: {{krabs_api_key}}
Content-Type: application/x-www-form-urlencoded

status=delivered


### Plankton's balance is now $90.01 (remember this amount)
GET /account/info
Authorization: {{plankton_auth}}

### Plankton requests a refund as soon as it's delivered
POST /orders/{{order_id}}/refund
Content-Type: application/x-www-form-urlencoded
Authorization: {{plankton_auth}}

amount=2.50

### Plankton tries to approve his own refund request using Chum Bucket Restaurant API key, but fails
PATCH /orders/{{order_id}}/refund/status
X-API-Key: {{chum_bucket_api_key}}
Content-Type: application/x-www-form-urlencoded

status=approved
?? status == 400

### Plankton tries to approve his own refund request using his basic auth credentials, and still no luck
PATCH /orders/{{order_id}}/refund/status
Content-Type: application/x-www-form-urlencoded
Authorization: {{plankton_auth}}

status=approved
?? status == 400

### Legitimate example: Krabs can reject the refund request
PATCH /orders/{{order_id}}/refund/status
X-API-Key: {{krabs_api_key}}
Content-Type: application/x-www-form-urlencoded

status=rejected
?? status == 200

### Refund status is rejected no matter what Plankton does... (or is there another way?)
GET /orders/{{order_id}}/refund/status
Authorization: {{plankton_auth}}

?? body status == rejected

### Plankton's balance is still $90.01
GET /account/info
Authorization: {{plankton_auth}}

?? body balance == 90.01