# Manual smoke test for signup flow
# Requires interactive input via @prompt - run manually in VSCode/httpyac GUI
@host = http://localhost:8000/api/v301

### Listing Menu Items (Public)
GET /menu

### Create a new user: should be already taken
POST /auth/register
Content-Type: application/json

{
    "email": "spongebob@bikinibottom.sea"
}

### Create a new user
POST /auth/register
Content-Type: application/json

{
    "email": "plankton.jr@chum-bucket.sea"
}

### Should fail
# @prompt token Get the token from verification email, using Mailpit UI: http://127.0.0.1:8025/
POST /auth/register
Content-Type: application/json

{
    "token": "{{token}}",
    "email": "spongebob@bikinibottom.sea",
    "password": "hijacked",
    "name": "SpongeBob"
}

### Check login attempt with fake password
GET /account/info
Authorization: Basic spongebob@bikinibottom.sea:whatever

### Check login attempt with hijacked credentials
GET /account/info
Authorization: Basic plankton.jr@chum-bucket.sea:hijacked
