# @import ../common/setup.http
@host = {{base_host}}/v101

### Listing Menu Items (Public)
GET /menu

?? status == 200

### Listing Sandy's Balance Before New Order
GET /account/credits
Authorization: {{sandy_auth}}

?? status == 200

### Listing Existing Orders (Customer)
GET /orders
Authorization: {{sandy_auth}}

?? status == 200

### Listing All Orders (Restaurant Manager)
GET /orders
X-API-Key: {{krabs_api_key}}

?? status == 200

### Place a New Order for a Krabby Patty
POST /orders
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

item=1

?? status == 201

### Listing Existing Orders
GET /orders
Authorization: {{sandy_auth}}

?? status == 200

### Listing Sandy's Balance After New Order
GET /account/credits
Authorization: {{sandy_auth}}

?? status == 200
