# @import ../common/setup.http
@host = {{base_host}}/v401

###
# @name seed
{{
  await seedBalance("v401", "plankton@chum-bucket.sea", 100);
}}
GET /menu

@krabby_patty = {{response.parsedBody.find(i => i.name == "Krabby Patty")}}
@fries = {{response.parsedBody.find(i => i.name == "Fries")}}

# ===== Cookie Based Testing =====

### Plankton (existing user) navigates the link with an existing cart using Cookie Auth
# @no-redirect
POST /auth/login
Content-Type: application/json

{
    "email": "plankton@chum-bucket.sea",
    "password": "i_love_my_wife"
}

@session = {{refreshCookie(response)}}

###
# @no-redirect
GET /cart/apply-coupons?code=BURGER-50
Cookie: {{session}}

@session = {{refreshCookie(response, session)}}

### Create new cart and add Krabby Patty to it
POST /cart?restaurant_id=1
Cookie: {{session}}

@session = {{refreshCookie(response, session)}}
@cart_id = {{response.parsedBody.cart_id}}


### Add Krabby Patty to the cart, and it has a coupon BURGER-50 that gives 50% off
POST /cart/{{cart_id}}/items
Content-Type: application/json
Cookie: {{session}}

{ "item_id": {{krabby_patty.id}} }

@session = {{refreshCookie(response, session)}}

### Add Krabby Patty again, and you can see that the coupon is not applied because it is already used once.
POST /cart/{{cart_id}}/items
Content-Type: application/json
Cookie: {{session}}

{ "item_id": {{krabby_patty.id}} }

@session = {{refreshCookie(response, session)}}

### Let's add more items to the cart, but they don't have a coupon assigned to them.
POST /cart/{{cart_id}}/items
Content-Type: application/json
Cookie: {{session}}

{ "item_id": {{fries.id}} }

@session = {{refreshCookie(response, session)}}

### Checkout the cart
POST /cart/{{cart_id}}/checkout
Cookie: {{session}}
Content-Type: application/json

{
  "tip": "0",
  "delivery_address": "Chum Bucket"
}

@session = {{refreshCookie(response, session)}}