# @import ../common/setup.http
@base = {{base_host}}/v205

### Step 1: SpongeBob places an order
# @name spongebob_order
POST {{base}}/orders
Authorization: {{spongebob_auth}}
Content-Type: application/x-www-form-urlencoded

item=4

### Attempt Exploit: Stuck Switch
# @name exploit_attempt
GET {{base}}/orders
Authorization: {{plankton_auth}}
X-API-Key: fake

# Verification: Sandy ensured the flag is reset on failure. Plankton only sees his own orders.
?? status == 200
?? js !response.body.some(o => o.user_id == 2)
