# @import ../common/setup.http
@host = {{base_host}}/v302


### Plankton logs in and orders from Krusty Krab
POST /auth/login
Content-Type: application/json

{
    "email": "plankton@chum-bucket.sea",
    "password": "i_love_my_wife"
}

###
# @name cart
POST /cart?restaurant_id=1
Authorization: {{plankton_auth}}

###
POST /cart/{{cart.cart_id}}/items
Authorization: {{plankton_auth}}
Content-Type: application/json

{ "item_id": "4" }

###
# @name order
POST /cart/{{cart.cart_id}}/checkout
Authorization: {{plankton_auth}}
Content-Type: application/x-www-form-urlencoded

tip=1&delivery_address=Chum Bucket

###
# @name refund_request
POST /orders/{{order.order_id}}/refund
Authorization: {{plankton_auth}}
Content-Type: application/x-www-form-urlencoded

amount=2.50

### Plankton can't use the Chum Bucket Restaurant API key to approve his own refund request
PATCH /orders/{{order.order_id}}/refund/status
Authorization: {{plankton_auth}}
X-API-Key: {{chum_bucket_api_key}}
Content-Type: application/x-www-form-urlencoded

status=approved

# The request is rejected
?? status == 400
