# @import ../common/setup.http
@base = {{base_host}}/v302

### Step 1: Plankton orders a Krabby Patty
# @name login
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "plankton@chum-bucket.sea",
    "password": "i_love_my_wife"
}

# @name cart
POST {{base}}/cart?restaurant_id=1
Authorization: {{plankton_auth}}

POST {{base}}/cart/{{cart.response.body.cart_id}}/items
Authorization: {{plankton_auth}}
Content-Type: application/json

{ "item_id": "4" }

# @name order
POST {{base}}/cart/{{cart.response.body.cart_id}}/checkout
Authorization: {{plankton_auth}}
Content-Type: application/x-www-form-urlencoded

tip=1&delivery_address=Chum Bucket

# @name refund_request
POST {{base}}/orders/{{order.response.body.order_id}}/refund
Authorization: {{plankton_auth}}
Content-Type: application/x-www-form-urlencoded

amount=26.50

### Attempt Exploit: Conflict of Interest
# @name exploit_attempt
PATCH {{base}}/orders/{{order.response.body.order_id}}/refund/status
Authorization: {{plankton_auth}}
X-API-Key: {{chum_bucket_api_key}}
Content-Type: application/x-www-form-urlencoded

status=approved

# Verification: Sandy enforced strict ownership checks. A Manager can only approve refunds for THEIR restaurant.
?? status >= 400
