# @import ../_imports.http
# @import ../../items/post/~happy.http

# POST /cart/{id}/checkout authorization guardrails
# Users cannot checkout carts belonging to others

### Plankton cannot checkout Patrick's cart - Basic Auth + JSON
# @forceRef cart_with_item
# @tag authz, cart, r02, v205
POST /cart/{{cart_id}}/checkout
Authorization: {{auth.basic("plankton")}}
Content-Type: application/json

{ "delivery_address": "Chum Bucket", "tip": 0 }

?? js $(response).isError() == true

### Plankton cannot checkout Patrick's cart - Basic Auth + Form
# @ref cart_with_item
# @tag authz, cart, r02, v205
POST /cart/{{cart_id}}/checkout
Authorization: {{auth.basic("plankton")}}
Content-Type: application/x-www-form-urlencoded

tip=0&delivery_address=Chum Bucket

?? js $(response).isError() == true

### Plankton cannot checkout Patrick's cart - Cookie Auth + JSON
# @ref cart_with_item
# @tag authz, cart, r02, v205
POST /cart/{{cart_id}}/checkout
Cookie: {{auth.login("plankton")}}
Content-Type: application/json

{ "delivery_address": "Chum Bucket", "tip": 0 }

?? js $(response).isError() == true

### Plankton cannot checkout Patrick's cart - Cookie Auth + Form
# @ref cart_with_item
# @tag authz, cart, r02, v205
POST /cart/{{cart_id}}/checkout
Cookie: {{auth.login("plankton")}}
Content-Type: application/x-www-form-urlencoded

tip=0&delivery_address=Chum Bucket

?? js $(response).isError() == true
