# @import ../_imports.http

# GET /account/info happy path
# Covers Basic Auth and Cookie Auth

### Basic Auth returns full account info
# @name info_basic_auth
{{
  await platform.seedCredits("plankton", 200);
  await platform.seedCredits("spongebob", 150);
}}
# @tag account, happy, r02, v205
GET /account/info
Authorization: {{auth.basic("plankton")}}

?? js $(response).isOk() == true
?? js $(response).hasFields("balance", "email") == true
?? js $(response).field("email") == {{user("plankton").email}}
?? js Number($(response).field("balance")) == 200

### Cookie Auth returns full account info
# @forceRef info_basic_auth
# @tag account, happy, r02, v205
GET /account/info
Cookie: {{auth.login("spongebob")}}

?? js $(response).isOk() == true
?? js $(response).hasFields("balance", "email") == true
?? js $(response).field("email") == {{user("spongebob").email}}
?? js Number($(response).field("balance")) == 150
