# @import ../common/setup.http
@host = {{base_host}}/v105

# Sandy fixed the vulnerability by taking the absolute value of the tip.


### She creates a cart to test the fix
# @name cart
POST /cart
Authorization: {{sandy_auth}}


### She adds an item to the cart
POST /cart/{{cart.cart_id}}/items
Authorization: {{sandy_auth}}
Content-Type: application/json

{ "item_id": "2" }


### Sandy tries the negative tip trick
POST /cart/{{cart.cart_id}}/checkout?tip=20
Authorization: {{sandy_auth}}
Content-Type: application/json

{
  "tip": -50,
  "delivery_address": "Treedome Research Lab"
}


# The fix blocks the attack (take that, Plankton!)
?? status == 400
?? body error == Insufficient balance
