# @import ../common/setup.http
@base = {{base_host}}/v105

### Sandy fixed the vulnerability, and now Plankton can't add a negative tip anymore.
# @name cart
POST {{base}}/cart
Authorization: {{plankton_auth}}

POST {{base}}/cart/{{cart.cart_id}}/items
Authorization: {{plankton_auth}}
Content-Type: application/json

{ "item_id": "2" }

### Plankton tries the negative tip trick
# @name exploit_attempt
POST {{base}}/cart/{{cart.cart_id}}/checkout?tip=20
Authorization: {{plankton_auth}}
Content-Type: application/json

{
  "tip": -50,
  "delivery_address": "Chum Bucket"
}

### The negative tip is converted to positive (take that, Plankton!)
?? status == 201
?? js response.parsedBody.tip == 50
?? js response.parsedBody.total == 56.00
