# @import ../common/setup.http
@base = {{base_host}}/v105

### Sandy prepares a cart
# @name cart
POST {{base}}/cart
Authorization: {{sandy_auth}}

POST {{base}}/cart/{{cart.response.body.cart_id}}/items
Authorization: {{sandy_auth}}
Content-Type: application/json

{ "item_id": "2" }

### She tries the negative tip trick
# @name exploit_attempt
POST {{base}}/cart/{{cart.response.body.cart_id}}/checkout?tip=20
Authorization: {{sandy_auth}}
Content-Type: application/json

{
  "tip": -50,
  "delivery_address": "Chum Bucket"
}

### The negative tip is converted to positive
?? status == 201
?? body.tip == "50.00"
?? body.total == "56.00"
