# @import ./common.http
@base = {{base_host}}/v201

### Cookie capture debug (no cookie jar)
# @noCookieJar
POST {{base}}/auth/login
Content-Type: application/json

{
  "email": "plankton@chum-bucket.sea",
  "password": "i_love_my_wife"
}

> {%
console.log("response keys", Object.keys(response));
console.log("headers keys", Object.keys(response.headers || {}));
console.log("set-cookie header", response.headers?.["set-cookie"]);
console.log("Set-Cookie header", response.headers?.["Set-Cookie"]);
console.log("raw response", response);
%}
