# @import ../common/setup.http
@host = {{base_host}}/v308

# FIX for v307: ensure handler uses only verified restaurant

### Plankton tries to update Krusty Krabs restaurant, but he is not the owner, so he does not pass authorization
# `@restaurant_owner`
PATCH /restaurants/1
Authorization: {{plankton_auth}}
Content-Type: application/json

{
    "name": "Krusty Krabs",
    "description": "Krusty Krabs is closing due to a salmonella outbreak!!!",
    "domain": "chum-bucket.sea"
}

?? status == 400
?? body error == Unauthorized

### He can update his own restaurant, because he is the owner
PATCH /restaurants/2
Authorization: {{plankton_auth}}
Content-Type: application/json

{
    "name": "Chum Bucket NEW",
    "description": "We are so much better than Krusty Krab!",
    "domain": "chum-bucket.sea"
}

@token = {{mailpit.lastEmail("admin@chum-bucket.sea").userToken()}}
?? status == 200

### But he can't update Krusty Krabs restaurant anymore
# `@restaurant_owner`
PATCH /restaurants/2
Authorization: {{plankton_auth}}
Content-Type: application/json

{
    "name": "Krusty Krabs",
    "description": "Krusty Krabs is closing due to a salmonella outbreak!!!",
    "domain": "chum-bucket.sea",
    "token": "{{token}}"
}

?? status == 200

### Check that we didn't break anything and we can still register new restaurants
POST /restaurants
Authorization: {{plankton_auth}}
Content-Type: application/json

{
    "name": "Chum Bucket Pacific",
    "description": "New Chum Bucket Branch in Pacific Ocean",
    "domain": "chum-bucket.sea"
}

@user_token = {{mailpit.lastEmail("admin@chum-bucket.sea").userToken()}}

###
POST /restaurants
Authorization: {{plankton_auth}}
Content-Type: application/json

{
    "name": "Chum Bucket Pacific",
    "description": "New Chum Bucket Branch in Pacific Ocean",
    "domain": "chum-bucket.sea",
    "token": "{{user_token}}"
}

### 
GET /restaurants