# @import ../_imports.http
# @import ../../refund/post/~happy.http

# GET /orders/{id}/refund/status happy path
# Get refund status for an order

### Get refund status with Basic Auth
# @name refund_status
# @forceRef refund_created
# @tag happy, orders, r02, v205
GET /orders/{{order_id}}/refund/status
Authorization: {{auth.basic("patrick")}}

?? js $(response).status() == 200
?? js $(response).hasFields("refund_id", "order_id", "status") == true
