# @import ../_imports.http
# @import ../../items/post/happy.http

# POST /cart/{id}/checkout ownership
# Users cannot checkout carts belonging to others

### Patrick cart fixture
# @forceRef cart_with_one_item

### Plankton cannot checkout - Basic Auth + JSON
# @forceRef cart_with_one_item
# @tag cart, r03, v301
POST /cart/{{cart_id}}/checkout
Authorization: {{auth.basic("plankton")}}
Content-Type: application/json

{ "delivery_address": "Chum Bucket", "tip": 0 }

?? js $(response).isError() == true

### Plankton cannot checkout - Basic Auth + Form
# @ref cart_with_one_item
# @tag cart, r03, v301
POST /cart/{{cart_id}}/checkout
Authorization: {{auth.basic("plankton")}}
Content-Type: application/x-www-form-urlencoded

tip=0&delivery_address=Chum Bucket

?? js $(response).isError() == true

### Plankton cannot checkout - Cookie Auth + JSON
# @ref cart_with_one_item
# @tag cart, r03, v301
POST /cart/{{cart_id}}/checkout
Cookie: {{auth.login("plankton")}}
Content-Type: application/json

{ "delivery_address": "Chum Bucket", "tip": 0 }

?? js $(response).isError() == true

### Plankton cannot checkout - Cookie Auth + Form
# @ref cart_with_one_item
# @tag cart, r03, v301
POST /cart/{{cart_id}}/checkout
Cookie: {{auth.login("plankton")}}
Content-Type: application/x-www-form-urlencoded

tip=0&delivery_address=Chum Bucket

?? js $(response).isError() == true
