# @import ../_imports.http

# POST /auth/logout happy path
# Session logout

### Logout with Cookie Auth
# @name logout
{{
  exports.plankton_session = await auth.login("plankton");
}}
# @tag auth, happy, r02, v205
POST /auth/logout
Cookie: {{plankton_session}}

?? js $(response).status() == 200
?? js $(response).hasField("message") == true
