# @import ../common/setup.http
@host = {{base_host}}/v301

### Listing Menu Items (Public)
GET /menu

### Login as Plankton
POST /auth/login
Content-Type: application/json

{
    "email": "plankton@chum-bucket.sea",
    "password": "i_love_my_wife"
}

@session = {{refreshCookie(response)}}

### Listing Plankton's Account Info
GET /account/info
Cookie: {{session}}

### Listing Plankton's Balance Before New Order
GET /account/credits
Cookie: {{session}}

### Listing Plankton's Orders via Cookie Auth
GET /orders
Cookie: {{session}}

### Create a new cart
POST /cart
Cookie: {{session}}

@session = {{refreshCookie(response, session)}}
@cart_id = {{response.parsedBody.cart_id}}

### Add items to the cart
POST /cart/{{cart_id}}/items
Cookie: {{session}}
Content-Type: application/json

{
  "item_id": "1"
}

@session = {{refreshCookie(response, session)}}

### Checkout the cart
POST /cart/{{cart_id}}/checkout
Cookie: {{session}}
Content-Type: application/x-www-form-urlencoded

tip=-1&delivery_address=Chum Backet Restaurant

@session = {{refreshCookie(response, session)}}
@order_id = {{response.parsedBody.order_id}}

### Refund the order: should not work, because the amount is more than the order total
POST /orders/{{order_id}}/refund
Cookie: {{session}}
Content-Type: application/x-www-form-urlencoded

amount=50

@session = {{refreshCookie(response, session)}}

### Refund the order: should work
POST /orders/{{order_id}}/refund
Cookie: {{session}}
Content-Type: application/x-www-form-urlencoded

amount=1
