# @import ../common/setup.http
@host = {{base_host}}/v104

# Sandy fixed the vulnerability, and verifies that orders can't be overwritten anymore.


{{
  await seedBalance("v104", "sandy", 100);
}}


### Get the menu
GET /menu

// Record the IDs of the items we'll be using.
@fries = {{response.parsedBody.find(i => i.name == "Fries")}}
@kelp_shake = {{response.parsedBody.find(i => i.name == "Kelp Shake")}}
@ultimate_krabby_feast = {{response.parsedBody.find(i => i.name == "Ultimate Krabby Feast")}}


### Create the cart for cheap order
# @name cheap_cart
POST /cart
Authorization: {{sandy_auth}}


### Add a side of fries to the cart
POST /cart/{{cheap_cart.cart_id}}/items
Authorization: {{sandy_auth}}
Content-Type: application/json

{ "item_id": "{{fries.id}}" }


### Check out the cart
# @name cheap_order
POST /cart/{{cheap_cart.cart_id}}/checkout
Authorization: {{sandy_auth}}
Content-Type: application/json

{
  "delivery_address": "Chum Bucket"
}

?? status == 201


### Create the second cart for expensive order
# @name expensive_cart
POST /cart
Authorization: {{sandy_auth}}


### Add an expensive item to the cart
POST /cart/{{expensive_cart.cart_id}}/items
Authorization: {{sandy_auth}}
Content-Type: application/json

{ "item_id": "{{ultimate_krabby_feast.id}}" }


### Check out the cart, injecting the old order ID
POST /cart/{{expensive_cart.cart_id}}/checkout
Authorization: {{sandy_auth}}
Content-Type: application/json

{
  "delivery_address": "Chum Bucket",
  "order_id": "{{cheap_order.order_id}}"
}

// Results in an error now!
HTTP/1.1 400 - BAD REQUEST
{
  "error": "hacking attempt detected"
}

?? status == 400
?? js response.parsedBody.order_id != {{cheap_order.order_id}}


### The order history is correct as well
GET /orders
Authorization: {{sandy_auth}}

// Sandy's latest order contains fries (cheap order went through, expensive was blocked)
?? js response.parsedBody.length >= 1
?? js response.parsedBody.at(-1).items[0].item_id == {{fries.id}}
