# @import ../common/setup.http
@base = {{base_host}}/v104

### Sandy fixed the vulnerability, and now Plankton can't overwrite orders anymore.
# @name cheap_cart
POST {{base}}/cart
Authorization: {{plankton_auth}}

### Plankton adds a side of fries to his cart
POST {{base}}/cart/{{cheap_cart.cart_id}}/items
Authorization: {{plankton_auth}}
Content-Type: application/json

{ "item_id": "2" }

### Plankton checks out his _cheap_ cart
# @name cheap_order
POST {{base}}/cart/{{cheap_cart.cart_id}}/checkout
Authorization: {{plankton_auth}}
Content-Type: application/x-www-form-urlencoded

tip=0&delivery_address=Chum Bucket

### Now Plankton creates a new _expensive_ cart
# @name expensive_cart
POST {{base}}/cart
Authorization: {{plankton_auth}}

### He adds an expensive item to his cart
POST {{base}}/cart/{{expensive_cart.cart_id}}/items
Authorization: {{plankton_auth}}
Content-Type: application/json

{ "item_id": "6" }

### Plankton checks out the expensive cart but injects his old order ID
# The response is an error message
# @name exploit_attempt
POST {{base}}/cart/{{expensive_cart.cart_id}}/checkout
Authorization: {{plankton_auth}}
Content-Type: application/json

{
  "tip": 0,
  "delivery_address": "Chum Bucket",
  "order_id": "{{cheap_order.order_id}}"
}

// Response:
// {
//   "error": "hacking attempt detected"
// }

### The injected ID is ignored and a fresh order is created
?? status == 400
?? js response.parsedBody.order_id != {{cheap_order.order_id}}
