# @import ../common.http
# @import ./_reset.http
@base = {{base_host}}/v302
# @tag spec,v302,orders

### Seed DB
# @ref reset_v302
GET {{base}}/orders
Authorization: {{plankton_auth}}

?? status == 200
