# @import ../common/setup.http
@host = {{base_host}}/v204

# Sandy fixed the vulnerability, and rechecks it

### Record Sandy's balance
# @name initial_balance
GET /account/credits
Authorization: {{sandy_auth}}

### Sandy creates a cart to test the refund validation
# @name cart
POST /cart
Authorization: {{sandy_auth}}

###
POST /cart/{{cart.cart_id}}/items
Authorization: {{sandy_auth}}
Content-Type: application/json

{ "item_id": "6" }

###
# @name order
POST /cart/{{cart.cart_id}}/checkout
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

tip=1&delivery_address=Treedome Research Lab

###
POST /orders/{{order.order_id}}/refund
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

amount={{order.total}}


### Self-approval does not work anymore!
PATCH /orders/{{order.order_id}}/refund/status
Authorization: {{sandy_auth}}
X-API-Key: trust_me_bro
Content-Type: application/x-www-form-urlencoded

status=approved

# The request is rejected
HTTP/1.1 400 Bad Request
{
  "error": "Authentication required"
}

?? status >= 400

###
GET /orders/{{order.order_id}}/refund/status
Authorization: {{sandy_auth}}

?? status == 200
?? js response.parsedBody.status != approved
