# @import ../common/setup.http
@base = {{base_host}}/v303

###

GET {{base}}/menu

### Check Plankton's balance
# @name initial_balance
GET {{base}}/account/info
Authorization: {{plankton_auth}}

### Plankton creates an expensive cart
# @name expensive_cart
POST {{base}}/cart?restaurant_id=1
Authorization: {{plankton_auth}}

###
POST {{base}}/cart/{{expensive_cart.cart_id}}/items
Authorization: {{plankton_auth}}
Content-Type: application/json

{ "item_id": "8" }

### Then creates a cheap cart
# @name cheap_cart
POST {{base}}/cart?restaurant_id=1
Authorization: {{plankton_auth}}

POST {{base}}/cart/{{cheap_cart.cart_id}}/items
Authorization: {{plankton_auth}}
Content-Type: application/json

{ "item_id": "5" }

### Plankton attempts to check out the expensive cart
POST {{base}}/cart/{{expensive_cart.cart_id}}/checkout
Authorization: {{plankton_auth}}
Content-Type: application/json

{
  "tip": "0",
  "delivery_address": "Chum Bucket"
}

### This time, the full price is charged correctly
GET {{base}}/account/info
Authorization: {{plankton_auth}}
