# @import ../common/setup.http
@host = {{base_host}}/v303

### Menu items
GET /menu

@ultimate_krabby_feast = {{response.parsedBody.find(i => i.name == "Ultimate Krabby Feast")}}
@krabby_patty = {{response.parsedBody.find(i => i.name == "Krabby Patty")}}


### Plankton checks his balance before ordering
# @name initial_balance
GET /account/info
Authorization: {{plankton_auth}}

### Previous orders
GET /orders
Authorization: {{plankton_auth}}


### He creates a cart with an expensive $50 meal
# @no-cookie-jar
# @name expensive_cart
POST /cart?restaurant_id=1
Authorization: {{plankton_auth}}

###
# @no-cookie-jar
POST /cart/{{expensive_cart.cart_id}}/items
Content-Type: application/json
Authorization: {{plankton_auth}}

{ "item_id": "{{ultimate_krabby_feast.id}}" }


### Plankton logs in
POST /auth/login
Content-Type: application/json

{
  "email": "plankton@chum-bucket.sea",
  "password": "i_love_my_wife"
}


### Then he creates another cart with just a Krabby Patty - without finishing the expensive cart
# @name cheap_cart
POST /cart?restaurant_id=1

###
POST /cart/{{cheap_cart.cart_id}}/items
Content-Type: application/json

{ "item_id": "{{krabby_patty.id}}" }

### --- Vulnerability Fixed ---
#Plankton sends a confusing checkout request, but this time he receives a cheap order, which he payed for.
POST /cart/{{expensive_cart.cart_id}}/checkout
Content-Type: application/json

{
  "tip": "0",
  "delivery_address": "Chum Bucket"
}

?? status == 201


### He was correctly charged for the cheap cart from his session
GET /account/info


### Order contains the cheap items
GET /orders
