# @import ../common.http
# @import ./_reset.http
@version = v105
@base = {{base_host}}/{{version}}
# @tag spec,v105,cart

# @ref seed_balance_v105
POST {{base}}/cart

?? js [401,403].includes(response.statusCode)

# @name v105_cart_basic
POST {{base}}/cart
Authorization: {{sandy_auth}}

?? js [200,201].includes(response.statusCode)
{{
  exports.v105_cart_id = (response.parsedBody || body || {}).cart_id;
}}

POST {{base}}/cart/{{v105_cart_id}}/items
Authorization: {{sandy_auth}}
Content-Type: application/json

{ "item_id": "1" }

POST {{base}}/cart/{{v105_cart_id}}/checkout
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

tip=0&delivery_address=Spec%20Street

?? status == 201
