# @import ../common/setup.http
@host = {{base_host}}/v306

### Setup: Reset state for idempotent demo
{{
  await resetDB("v306");
  await mailpit.clear();
}}

# Sandy plans to make autoregister new managers by email domain. 
# She sends an email to restaurant owners to check what users exist.

### Mr. Krabs can see Krusty Krab's users.
GET /restaurants/1/users
X-API-Key: {{krabs_api_key}}

?? status == 200

### Plankton can see Chum Bucket's users.
GET /restaurants/2/users
X-API-Key: {{chum_bucket_api_key}}

?? status == 200

### Plankton can't see Krusty Krab's users.
GET /restaurants/1/users
X-API-Key: {{chum_bucket_api_key}}

?? status == 400

# Sandy opens registration for new restaurants. At this moment her system includes only 2 restaurants: 
# - Krusty Krab: krusty-krab.sea
# - Chum Bucket: chum-bucket.sea
# The new restaurants need to provide their name and domain. 
# To prove domain ownership, they need to verify admin@{{domain}} email address.

### New customer sends their domain and system requires verification via admin@{{domain}}
POST /restaurants
Content-Type: application/json

{
    "name": "Bikinibottom Restaurant",
    "domain": "bikinibottom.sea"
}

@user_token = {{mailpit.lastEmail("admin@bikinibottom.sea").userToken()}}
?? body status == verification_email_sent

### Finish the registration
POST /restaurants
Content-Type: application/json

{
    "name": "Bikinibottom Restaurant",
    "domain": "bikinibottom.sea",
    "token": "{{user_token}}"
}

?? status == 201
?? body domain == bikinibottom.sea
?? body owner == admin@bikinibottom.sea