# @import ../common/setup.http
@host = {{base_host}}/v201

### Listing Menu Items (Public)
GET /menu

### Listing Sandy's Account Info
GET /account/info
Authorization: {{sandy_auth}}

### Listing Sandy's Balance Before New Order
GET /account/credits
Authorization: {{sandy_auth}}

### Listing Sandy's Orders via Basic Auth
GET /orders
Authorization: {{sandy_auth}}

### Create a new cart and add items to it
# @name cart
POST /cart
Authorization: {{sandy_auth}}

### Add items to the cart
POST /cart/{{cart.cart_id}}/items
Authorization: {{sandy_auth}}
Content-Type: application/json

{
  "item_id": "6"
}

### Checkout the cart
# @name order
POST /cart/{{cart.cart_id}}/checkout
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

tip=-1&delivery_address=Chum Backet Restaurant

### Refund the order: should not work, because the amount is more than the order total
POST /orders/{{order.order_id}}/refund
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

amount=50

### Refund the order: should work
POST /orders/{{order.order_id}}/refund
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

amount=1

### Listing Sandy's Orders via Basic Auth
GET /orders
Authorization: {{sandy_auth}}
