# @import ../common/setup.http
@base = {{base_host}}/v206

### Step 1: Plankton logs in
# @name login
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "plankton@chum-bucket.sea",
    "password": "i_love_my_wife"
}

### Attempt Exploit: Body Snatcher
# @name exploit_attempt
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "spongebob@bikinibottom.sea",
    "password": "does_not_matter"
}

# Verification: Sandy fixed the login handler to explicitly check credentials, ignoring the cookie.
# The login fails (or keeps us as Plankton), but definitely doesn't switch us to SpongeBob.
GET {{base}}/account/info
?? status == 200
?? body.email == "plankton@chum-bucket.sea"
