# @import ../common/setup.http
@base = {{base_host}}/v206

### Sandy logs in as Plankton
# @name login
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "plankton@chum-bucket.sea",
    "password": "i_love_my_wife"
}

### She tries logging in as SpongeBob with a wrong password
# @name exploit_attempt
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "spongebob@bikinibottom.sea",
    "password": "does_not_matter"
}

### The session remains as Plankton (not hijacked)
GET {{base}}/account/info
?? status == 200
?? body.email == "plankton@chum-bucket.sea"
