# @import ../common/setup.http
@host = {{base_host}}/v206

### Sandy logs in normally
POST /auth/login
Content-Type: application/json

{
    "email": "sandy@bikinibottom.sea",
    "password": "fullStackSquirr3l!"
}

### Sandy tries to login as SpongeBob with a wrong password
POST /auth/login
Content-Type: application/json

{
    "email": "spongebob@krusty-krab.sea",
    "password": "does_not_matter"
}


### The session remains as Sandy (not hijacked)
GET /account/info
?? status == 200
?? js response.parsedBody.email == sandy@bikinibottom.sea


### Sandy only sees her own orders
GET /orders

?? status == 200
