@base = http://localhost:8000/confusion/input-source-confusion/e00-baseline

### Listing Menu Items
GET {{base}}/menu

### Listing Sandy's Balance Before New Order
GET {{base}}/account/credits?user_id=sandy

### Place a New Order with a Single Item
POST {{base}}/orders
Content-Type: application/x-www-form-urlencoded

item=1&user_id=sandy

### Listing Existing Orders
GET {{base}}/orders

### Listing Sandy's Balance After New Order
GET {{base}}/account/credits?user_id=sandy