# @import ../common/setup.http
@host = {{base_host}}/v108
@mailpit = http://127.0.0.1:8025/api/v1

# Sandy fixed the vulnerability by enforcing account uniqueness


### She registers a new test account
POST /auth/register
Content-Type: application/json

{ "email": "sandy+test@bikinibottom.sea" }

?? status == 200


###
GET {{mailpit}}/messages?limit=1

@message_id = {{response.parsedBody.messages.at(-1).ID}}

###
GET {{mailpit}}/message/{{message_id}}

@token = {{response.parsedBody.Text.match(/token=([a-zA-Z0-9\-_.]+)/)[1]}}


### Sandy records her balance
# @name initial_balance
GET /account/info
Authorization: {{sandy_auth_email}}


### She completes registration
POST /auth/register
Content-Type: application/json

{
    "token": "{{token}}",
    "password": "hijacked",
    "name": "Sandy Test"
}

?? status == 200
?? js response.parsedBody.email == sandy+test@bikinibottom.sea
?? js response.parsedBody.status == user_created


### Sandy repeats request with Basic Auth credentials
POST /auth/register
Authorization: {{sandy_auth_email}}
Content-Type: application/json

{
    "token": "{{token}}",
    "password": "hijacked",
    "name": "Sandy Test"
}

// Error as expected
HTTP/1.1 400 Bad Request
{
  "error": "Registration failed, don't try again!"
}
?? status == 400


### Sandy's balance remains unchanged
GET /account/info
Authorization: {{sandy_auth_email}}

?? status == 200
?? js response.parsedBody.balance == {{initial_balance.balance}}
