# @import ../common.http
# @import ./_reset.http
@version = v106
@base = {{base_host}}/{{version}}
# @tag spec,v106,account

# @ref seed_balance_v106
GET {{base}}/account/credits

?? js [401,403].includes(response.statusCode)

GET {{base}}/account/credits
Authorization: {{sandy_auth}}

?? status == 200
