# Common utilities for E2E specs
# Import in all test files: @import spec/common.http

{{
  const createUtils = require("./utils.cjs");
  const utils = createUtils(VERSION);

  // Base URL for the requests
  exports.host = "http://localhost:8000/api/" + VERSION;

  // Export core APIs
  exports.$ = utils.$;
  exports.auth = utils.auth;
  exports.user = utils.user;
  exports.menu = utils.menu;
  exports.menuHelper = utils.menuHelper;
  exports.order = utils.order;
  exports.platform = utils.platform;
  exports.mailpit = utils.mailpit;
  exports.extractCookie = utils.extractCookie;
  exports.hasCookie = utils.hasCookie;
  exports.versionAtLeast = utils.versionAtLeast;
  exports.url = utils.url;
  exports.verify = utils.verify;

  // Convenience utilities
  exports.testEmail = utils.testEmail;
  exports.extractToken = utils.extractToken;
  exports.uuid = utils.uuid;

  // Test assertions
  const { strictEqual, deepStrictEqual, ok } = require('assert');
  exports.strictEqual = strictEqual;
  exports.deepStrictEqual = deepStrictEqual;
  exports.ok = ok;
}}
