# @import ../common.http
@base = {{base_host}}/v202

### Reset in-memory state
# @name reset_v202
POST {{base}}/platform/reset
X-Admin-API-Key: {{admin_key}}

### Seed balances
# @name seed_balance_v202
# @ref reset_v202
POST {{base}}/platform/balance
X-Admin-API-Key: {{admin_key}}
Content-Type: application/json

{ "user_id": "sandy@bikinibottom.sea", "balance": 200 }
