# @import ../_imports.http
# @import ../../../cart/checkout/post/happy.http

# GET /orders happy path
# Customer-scoped order listings

### Customer sees own orders - Basic Auth
# @name orders_basic
# @forceRef new_order
# @tag happy, orders, r02, v201
GET /orders
Authorization: {{auth.basic("patrick")}}

?? js $(response).isOk() == true
?? js $(response).hasOnlyUserData("patrick") == true

### Customer sees own orders - Cookie Auth
# @name orders_cookie
# @ref orders_basic
# @tag happy, orders, r02, v201
GET /orders
Cookie: {{auth.login("patrick")}}

?? js $(response).isOk() == true
?? js $(response).hasOnlyUserData("patrick") == true
