@base = http://localhost:8000/api/v106

### Vulnerable Example FIXED:

### Create a cart
# @name cart
POST {{base}}/cart
Authorization: Basic sandy:testpassword

### Add an item to the cart
POST {{base}}/cart/{{cart.response.body.cart_id}}/items
Authorization: Basic sandy:testpassword
Content-Type: application/json

{
  "item_id": "1"
}

### Checkout the cart
# @name order
POST {{base}}/cart/{{cart.response.body.cart_id}}/checkout
Authorization: Basic sandy:testpassword
Content-Type: application/x-www-form-urlencoded

tip=3&delivery_address=124 Conch Street

### Legitimate refund: $1
POST {{base}}/orders/{{order.response.body.order_id}}/refund
Authorization: Basic sandy:testpassword
Content-Type: application/json

{
  "amount": "1"
}

### Refund $50: it is more expensive than the order total and will be rejected
POST {{base}}/orders/{{order.response.body.order_id}}/refund
Authorization: Basic sandy:testpassword
Content-Type: application/json

{
  "amount": "50"
}

### Vulnerable Example FIXED: now we check both the body form and the JSON body:
# Again, $50 is more than the order total and will be rejected
POST {{base}}/orders/{{order.response.body.order_id}}/refund
Authorization: Basic sandy:testpassword
Content-Type: application/x-www-form-urlencoded

amount=50

### Check balance: Sandy received refund for $1
GET {{base}}/account/credits
Authorization: Basic sandy:testpassword