# @import ../common.http
# @import ./_reset.http
@base = {{base_host}}/v303
# @tag spec,v303,orders

### Seed DB
# @ref reset_v303
GET {{base}}/orders
Authorization: {{plankton_auth}}

?? status == 200
