# @import ../common.http
# @import ./_reset.http
@version = v107
@base = {{base_host}}/{{version}}
# @tag spec,v107,orders

# @ref seed_balance_v107
GET {{base}}/orders

?? js [400,401,403].includes(response.statusCode)

GET {{base}}/orders
Authorization: {{sandy_auth}}

?? status == 200
