# @import ../common/setup.http
@host = {{base_host}}/v304

# v304 fixes the cross-tenant menu edit vulnerability from v303


### Plankton checks the Krusty Krab menu
GET /menu

@fries = {{response.parsedBody.find(i => i.name.includes("Fries"))}}


### Plankton tries to sabotage Krusty Krab's menu - but the fix blocks him
PATCH /menu/{{fries.id}}
X-API-Key: {{chum_bucket_api_key}}
Content-Type: application/json

{
  "available": false,
  "name": "Fries (SALMONELLA OUTBREAK)"
}

?? status == 400


### The Fries are safe - Plankton's attack was blocked
GET /menu

?? js response.parsedBody.find(i => i.name.includes("SALMONELLA")) == undefined
