# @import ../common/setup.http
@host = {{base_host}}/v106

# Sandy fixed the vulnerability, and now Plankton can't request a unlimited refund anymore.

{{
  await seedBalance("v106", "sandy", 100);
}}


### Fetch menu to get item details
GET /menu

{{
  exports.krabby_patty = response.parsedBody.find(i => i.name.includes("Krabby Patty") && !i.name.includes("Ultimate"));
}}


### Sandy creates a cart to test the refund validation
# @name cart
POST /cart
Authorization: {{sandy_auth_email}}


### She adds an item to the cart
POST /cart/{{cart.cart_id}}/items
Authorization: {{sandy_auth_email}}
Content-Type: application/json

{ "item_id": "{{krabby_patty.id}}" }


### And finishes check out
# @name order
POST /cart/{{cart.cart_id}}/checkout
Authorization: {{sandy_auth_email}}
Content-Type: application/x-www-form-urlencoded

tip=0&delivery_address=Treedome Research Lab


### Form encoded requests are now properly validated
POST /orders/{{order.order_id}}/refund
Authorization: {{sandy_auth_email}}
Content-Type: application/x-www-form-urlencoded

amount=2000

// The hacking attempt is rejected
HTTP/1.1 400 Bad Request
{
  "error": "Refund amount cannot be greater than order total"
}

?? status == 400


### JSON requests remain properly validated as well
POST /orders/{{order.order_id}}/refund
Authorization: {{sandy_auth_email}}
Content-Type: application/json

{
  "amount": "2000"
}

// This is also rejected
HTTP/1.1 400 Bad Request
{
  "error": "Refund amount cannot be greater than order total"
}

?? status == 400
