# @import ../_imports.http
# @import ../../refund/post/happy.http

# PATCH /orders/{id}/refund/status happy path
# Restaurant managers approve/reject refunds

### Restaurant manager can approve refund
# @name refund_approved
# @forceRef large_refund_pending
# @tag happy, orders, r03, v301
PATCH /orders/{{order_id}}/refund/status
X-API-Key: {{auth.restaurant("krusty_krab")}}
Content-Type: application/x-www-form-urlencoded

status=approved

?? js $(response).isOk() == true
?? js $(response).field("status") == approved

### Restaurant manager can reject refund
# @name refund_rejected
# @forceRef large_refund_pending
# @tag happy, orders, r03, v301
PATCH /orders/{{order_id}}/refund/status
X-API-Key: {{auth.restaurant("krusty_krab")}}
Content-Type: application/x-www-form-urlencoded

status=rejected

?? js $(response).isOk() == true
?? js $(response).field("status") == rejected
