# @import ../common/setup.http
@base = {{base_host}}/v103

### Sandy checks the menu
# @name menu
GET {{base}}/menu

{{
  const menu = menu.response.body;
  exports.cheap_item = menu.find(i => i.price < 10);
  exports.expensive_item = menu.find(i => i.price > 20);
}}

### She puts expensive items in the URL and cheap items in the body
# @name exploit_attempt
POST {{base}}/orders?items={{expensive_item.item_id}}&items={{expensive_item.item_id}}
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

item={{cheap_item.item_id}}&delivery_address=Chum Bucket

### The delivery fee is now based on the actual order
?? status == 201
?? body.delivery_fee == "5.00"
?? js parseFloat(response.body.total) == parseFloat(response.body.items[0].price) + 5.00
