# @import ../common/setup.http
@host = {{base_host}}/v203

# Sandy fixed the vulnerability, and now data from body is ignored for updating balance if the request is not from the platform admin


### Sandy checks her own balance
# @name initial_balance
GET /account/credits
Authorization: {{sandy_auth}}

?? js response.parsedBody.email == sandy@bikinibottom.sea


### Regular customers can't add credits anymore
GET /account/credits
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

user=sandy@bikinibottom.sea&amount=100

### The balance remains unchanged
?? status == 200
?? js parseFloat(response.parsedBody.balance) == parseFloat(initial_balance.balance)
