# @import ../common/setup.http
@host = {{base_host}}/v102

### Sandy fixes the vulnerability, so now `item` parameter is ignored.
GET /menu

// Record the cheapest and most expensive items from the menu
@cheap_item = {{response.parsedBody.find(i => parseFloat(i.price) < 5)}}
@expensive_item = {{response.parsedBody.find(i => parseFloat(i.price) > 20)}}


### Get her balance before the exploit
# @name initial_balance
GET /account/credits
Authorization: {{sandy_auth}}


### She verifies that sending both parameters together results in the expensive item being paid for.
POST /orders
Authorization: {{sandy_auth}}
Content-Type: application/x-www-form-urlencoded

item={{cheap_item.id}}&items={{expensive_item.id}}

// Price and items are now consistent
?? status == 201
?? js response.parsedBody.total == {{expensive_item.price}}
?? js response.parsedBody.items[0].price == {{expensive_item.price}}


### The balance is deducted correctly
GET /account/credits
Authorization: {{sandy_auth}}

{{
  const initial_credits = parseFloat(initial_balance.balance);
  const final_credits = parseFloat(response.parsedBody.balance);
  const deducted = initial_credits - final_credits;
  console.info(`Deducted amount: ${deducted.toFixed(2)} (should equal expensive item price: ${expensive_item.price}})`);
}}


### The order history is correct as well
GET /orders
Authorization: {{sandy_auth}}
