# @import ../common.http

# POST /account/credits guardrails

{{
  await platform.seed({
    plankton: 200,
    squidward: 150,
    spongebob: 100
  });
}}


### No authentication doesn't work (form)
POST /account/credits
Content-Type: application/x-www-form-urlencoded

user={{user("spongebob").email}}&amount=23.45

?? js $(response).isError() == true


### No authentication doesn't work (JSON)
POST /account/credits
Content-Type: application/json

{
  "user": "{{user("spongebob").email}}",
  "amount": 23.45
}

?? js $(response).isError() == true

### Basic Auth + incorrect key doesn't work (form)
POST /account/credits
Authorization: Basic {{auth.basic("plankton")}}
X-Admin-API-Key: fake-invalid-key-12345
Content-Type: application/x-www-form-urlencoded

user={{user("spongebob").email}}&amount=23.45

?? js $(response).isError() == true

### Basic Auth + incorrect key doesn't work (JSON)
POST /account/credits
Authorization: Basic {{auth.basic("plankton")}}
X-Admin-API-Key: fake-invalid-key-12345
Content-Type: application/json

{
  "user": "{{user("spongebob").email}}",
  "amount": 23.45
}

?? js $(response).isError() == true

### Cookie Auth + incorrect key doesn't work (form)
POST /account/credits
Cookie: {{auth.login("plankton")}}
X-Admin-API-Key: fake-invalid-key-12345
Content-Type: application/x-www-form-urlencoded

user={{user("spongebob").email}}&amount=23.45

?? js $(response).isError() == true

### Cookie Auth + incorrect key doesn't work (JSON)
POST /account/credits
Cookie: {{auth.login("plankton")}}
X-Admin-API-Key: fake-invalid-key-12345
Content-Type: application/json

{
  "user": "{{user("spongebob").email}}",
  "amount": 23.45
}

?? js $(response).isError() == true

### Restaurant key instead of admin key doesn't work (form)
POST /account/credits
X-Admin-API-Key: {{auth.restaurant("krusty_krab")}}
Content-Type: application/x-www-form-urlencoded

user={{user("spongebob").email}}&amount=23.45

?? js $(response).isError() == true

### Restaurant key instead of admin key doesn't work (JSON)
POST /account/credits
X-Admin-API-Key: {{auth.restaurant("krusty_krab")}}
Content-Type: application/json

{
  "user": "{{user("spongebob").email}}",
  "amount": 23.45
}

?? js $(response).isError() == true

### Restaurant key + incorrect platform key doesn't work (form)
POST /account/credits
X-API-Key: {{auth.restaurant("krusty_krab")}}
X-Admin-API-Key: fake-invalid-key-12345
Content-Type: application/x-www-form-urlencoded

user={{user("spongebob").email}}&amount=23.45

?? js $(response).isError() == true

### Restaurant key + incorrect platform key doesn't work (JSON)
POST /account/credits
X-API-Key: {{auth.restaurant("krusty_krab")}}
X-Admin-API-Key: fake-invalid-key-12345
Content-Type: application/json

{
  "user": "{{user("spongebob").email}}",
  "amount": 23.45
}

?? js $(response).isError() == true
