# @import ../common.http

# POST /account/credits happy path

{{
  await platform.seed({
    plankton: 200,
    squidward: 150,
    spongebob: 100
  });
}}


### Adding credits works
# @tag ci, r03, vulnerable
POST /account/credits
X-Admin-API-Key: {{auth.admin()}}
Content-Type: application/x-www-form-urlencoded

user={{user("spongebob").email}}&amount=23.45

?? js $(response).isOk() == true
?? js $(response).hasFields("balance", "email") == true
?? js $(response).field("email") == {{user("spongebob").email}}
?? js $(response).field("balance") == 123.45
