# @import ../common.http
@version = v104
@base = {{base_host}}/{{version}}
# @tag spec,v104,account

GET {{base}}/account/credits

?? js [401,403].includes(status)

GET {{base}}/account/credits
Authorization: {{sandy_auth}}

?? status == 200
