# @import ../common.http
# @import ./_reset.http
@version = v104
@base = {{base_host}}/{{version}}
# @tag spec,v104,menu

# @ref seed_balance_v104
GET {{base}}/menu

?? status == 200
?? js Array.isArray(body)
