services:
  app:
    extends:
      file: compose.yml
      service: app
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: requirements.txt
